import oracledb from 'oracledb';
import { withConnection, withTransaction } from '../../config/database';
export interface AppointmentInput { customerId: number; serviceId: number; startAt: Date; endAt: Date; source: 'WEB' | 'WHATSAPP' | 'ADMIN'; notes?: string | null }
export interface AppointmentRow { appointmentId: number; customer: string; service: string; startAt: Date; endAt: Date; status: string; source: string; notes: string | null }
const base = `SELECT A.APPOINTMENT_ID AS "appointmentId", TRIM(C.FIRST_NAME || ' ' || NVL(C.LAST_NAME,'')) AS "customer", S.NAME AS "service", A.START_AT AS "startAt", A.END_AT AS "endAt", A.STATUS AS "status", A.SOURCE AS "source", A.NOTES AS "notes" FROM APPOINTMENTS A JOIN CUSTOMERS C ON C.CUSTOMER_ID=A.CUSTOMER_ID JOIN SERVICES S ON S.SERVICE_ID=A.SERVICE_ID WHERE A.BARBER_ID=:barberId`;
export async function listAppointments(barberId: number, page: number, limit: number): Promise<AppointmentRow[]> { return withConnection(async c => (await c.execute<AppointmentRow>(`${base} ORDER BY A.START_AT DESC OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY`, { barberId, offset: (page - 1) * limit, limit }, { outFormat: oracledb.OUT_FORMAT_OBJECT })).rows ?? []); }
export async function listToday(barberId: number): Promise<AppointmentRow[]> { return withConnection(async c => (await c.execute<AppointmentRow>(`${base} AND A.START_AT >= TRUNC(SYSDATE) AND A.START_AT < TRUNC(SYSDATE)+1 ORDER BY A.START_AT`, { barberId }, { outFormat: oracledb.OUT_FORMAT_OBJECT })).rows ?? []); }
export async function nextAppointment(barberId: number): Promise<AppointmentRow | null> { return withConnection(async c => { const r = await c.execute<AppointmentRow>(`${base} AND A.START_AT > SYSTIMESTAMP AND A.STATUS IN ('PENDING','CONFIRMED') ORDER BY A.START_AT FETCH FIRST 1 ROW ONLY`, { barberId }, { outFormat: oracledb.OUT_FORMAT_OBJECT }); return r.rows?.[0] ?? null; }); }
export async function createAppointment(barberId: number, input: AppointmentInput): Promise<number> { return withTransaction(async c => { const r = await c.execute(`BEGIN PKG_APPOINTMENT.CREATE_APPOINTMENT(:barberId,:customerId,:serviceId,:startAt,:endAt,:source,:notes,:appointmentId); END;`, { barberId, ...input, appointmentId: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER } }); return (r.outBinds as { appointmentId: number }).appointmentId; }); }
export async function cancelAppointment(barberId: number, appointmentId: number): Promise<void> { await withTransaction(c => c.execute(`BEGIN PKG_APPOINTMENT.CANCEL_APPOINTMENT(:appointmentId,:barberId); END;`, { appointmentId, barberId })); }
