import oracledb from 'oracledb';
import { withConnection, withTransaction } from '../../config/database';
export interface ScheduleInput { dayOfWeek: number; startTime: Date; endTime: Date }
export interface ExceptionInput { exceptionDate: Date; startTime?: Date | null; endTime?: Date | null; type: 'DAY_OFF' | 'VACATION' | 'BLOCK' | 'SPECIAL_HOURS'; reason?: string | null }
export async function listSchedules(barberId: number): Promise<Record<string, unknown>[]> { return withConnection(async c => (await c.execute<Record<string, unknown>>(`SELECT SCHEDULE_ID AS "scheduleId", DAY_OF_WEEK AS "dayOfWeek", START_TIME AS "startTime", END_TIME AS "endTime", STATUS AS "status" FROM SCHEDULES WHERE BARBER_ID=:barberId ORDER BY DAY_OF_WEEK, START_TIME`, { barberId }, { outFormat: oracledb.OUT_FORMAT_OBJECT })).rows ?? []); }
export async function listExceptions(barberId: number): Promise<Record<string, unknown>[]> { return withConnection(async c => (await c.execute<Record<string, unknown>>(`SELECT EXCEPTION_ID AS "exceptionId", EXCEPTION_DATE AS "exceptionDate", START_TIME AS "startTime", END_TIME AS "endTime", TYPE AS "type", REASON AS "reason" FROM SCHEDULE_EXCEPTIONS WHERE BARBER_ID=:barberId ORDER BY EXCEPTION_DATE`, { barberId }, { outFormat: oracledb.OUT_FORMAT_OBJECT })).rows ?? []); }
export async function createSchedule(barberId: number, input: ScheduleInput): Promise<number> { return withTransaction(async c => { const r = await c.execute(`BEGIN PKG_SCHEDULE.CREATE_SCHEDULE(:barberId,:dayOfWeek,:startTime,:endTime,:scheduleId); END;`, { barberId, ...input, scheduleId: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER } }); return (r.outBinds as { scheduleId: number }).scheduleId; }); }
export async function deleteSchedule(barberId: number, scheduleId: number): Promise<void> { await withTransaction(c => c.execute(`BEGIN PKG_SCHEDULE.DELETE_SCHEDULE(:scheduleId,:barberId); END;`, { scheduleId, barberId })); }
export async function createException(barberId: number, input: ExceptionInput): Promise<number> { return withTransaction(async c => { const r = await c.execute(`BEGIN PKG_SCHEDULE.CREATE_EXCEPTION(:barberId,:exceptionDate,:startTime,:endTime,:type,:reason,:exceptionId); END;`, { barberId, ...input, exceptionId: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER } }); return (r.outBinds as { exceptionId: number }).exceptionId; }); }
